#!/bin/Rscript
#Author: Enrico Moiso
#email: em.metaminer@gmail.com
#Date: 09/23/2019

#this files generate the plot for the follwoing panels fig2B-D,figS1D, fis4A-B
#2 z1 files generated by data_recap.R for each TCGA tumor/sample type have to pulled together to create full_z
#3 full_z_mean_df is a dataframe of 56 rows (MOCA sub trajectories) and a variable amount of TCGA samples (depending of how many saple type data_recap.R has been run on). In this case it only contains primary tumors, metastatis and normal samples.

#color scheme for umaps
library(RColorBrewer)
library(pheatmap)
library(viridis)
library(ggplot2)
library(reshape2)
library(ggpubr)
f_colore_rb9_i=function(x){
  library(RColorBrewer)
  
  y=ifelse(x<=(-3),rev(brewer.pal(9, 'Blues'))[1],
           ifelse(x<=(-2)&x>(-3),rev(brewer.pal(9, 'Blues'))[3],
                  ifelse(x<=(-1)&x>(-2),rev(brewer.pal(9, 'Blues'))[5],
                         ifelse(x<=(-.5)&x>(-1),rev(brewer.pal(9, 'Blues'))[7],
                                ifelse(x<=(.5)&x>(-.5),'gray90',
                                       ifelse(x<=(1)&x>(.5),rev(brewer.pal(9, 'Reds'))[7],
                                              ifelse(x<=(2)&x>1,rev(brewer.pal(9, 'Reds'))[5],
                                                     ifelse(x<=(3)&x>2,rev(brewer.pal(9, 'Reds'))[3],
                                                            rev(brewer.pal(9, 'Reds'))[1]))))))))
  y
}
f_colore_vi=function(x){
  require(viridis)
  y=ifelse(x==9.5, viridis(5)[1],
           ifelse(x==10.5, viridis(5)[2],
                  ifelse(x==11.5,viridis(5)[3],
                         ifelse(x==12.5,viridis(5)[4],
                                viridis(5)[5]))))
  y
}

#annotation data load
load('dep_files/cell_annotations.rsave')
#fig2b, fig12 and figs1d data !!-> 1.6Gb unzipped, it takes some time to load
full_z=read.delim('dep_files/data_fig2bd_figs1d_tcga_moca.csv.gz',sep=',',stringsAsFactors = F)
#fig2c data
full_z_mean_df=read.delim('dep_files/data_fig2c_figs4a.csv.gz',sep=',',stringsAsFactors = F)
rownames(full_z_mean_df)=full_z_mean_df$Sub_trajectory_name
full_z_mean_df=full_z_mean_df[,-1]
#fig2e,f data
devtime_tissue=read.delim('dep_files/data_fig2ef.csv',stringsAsFactors = F,sep = ',')
devtime_tissue$v2.Var1=gsub('^', 'E',devtime_tissue$v2.Var1)
devtime_tissue$v2.Var1=factor(devtime_tissue$v2.Var1,levels = unique(devtime_tissue$v2.Var1)[c(5,1:4)])
colnames(devtime_tissue)[2]='Embryonic_Period'
#calculation of enrichmnet by means of chi-sqared distribution residuals between the counts (v2.freq), the tissue type and the time variable
devtime_enrichment=reshape2::melt(chisq.test(t(xtabs(v2.Freq~Embryonic_Period+tissue, data=devtime_tissue)))$residuals)

#creates annotations and colors for heatmaps 
{annotazioni_t=data.frame(row.names = rownames(full_z_mean_df),
                         Main_trajectory=gsub('trajectory','',full_z$Main_trajectory_refined_by_cluster[match(rownames(full_z_mean_df), full_z$Sub_trajectory_name)])
                         ,stringsAsFactors = T)
annotazioni_s=data.frame(row.names = colnames(full_z_mean_df),
                         Tissue_type=gsub('TB', 'TP',unlist(lapply(strsplit(colnames(full_z_mean_df), '_'),'[',2))),
                         Tumor=unlist(lapply(strsplit(colnames(full_z_mean_df), '_'),'[',1)),stringsAsFactors = T)
mycolors2=list(Main_trajectory = c('brown','burlywood','tomato','lightsalmon','thistle','darkolivegreen','dodgerblue','deepskyblue','blue','navy'),
               Tissue_type=c('lawngreen','thistle','cadetblue'),
               Tumor=c('goldenrod4',#ACC
                       'mistyrose2',#Blca
                       'maroon1',#brca
                       'orange',#cesc
                       'blue4',#chol
                       'cyan',#coad
                       'indianred',#dlbc
                       'chartreuse4',#esca
                       'dodgerblue',#gbm
                       'darkseagreen',#hnsc
                       'brown1',#kich
                       'brown2',#kirc
                       'brown3', #kirp
                       'tan4',#laml
                       'dodgerblue4',#lgg
                       'lightsteelblue',#lihc
                       'plum',#luad
                       'plum4',#lusc
                       'purple4',#meso
                       'orange3',#ov
                       'lightsteelblue4',#paad
                       'darkgoldenrod2',#pcpg
                       'darkred',#prad
                       'cyan4',#read
                       'aquamarine4',#sarc
                       'darkkhaki',#skcm
                       'chartreuse',#stad
                       'red',#tgct
                       'gold',#thca
                       'tan',#thym
                       'peachpuff',#ucec
                       'darkorange',#ucs
                       'darkgreen'#uvm
               ))
names(mycolors2$Main_trajectory) <- levels(annotazioni_t$Main_trajectory)
names(mycolors2$Tissue_type) <- levels(annotazioni_s$Tissue_type)
names(mycolors2$Tumor) <- sort(unique(unlist(lapply(strsplit(colnames(full_z_mean_df), '_'),'[',1))))
}
#create clustering for tcga samples and subtrajectories
full_z_scores_hct=hclust(dist(full_z_mean_df), method = 'ward.D')
full_z_scores_hcs=hclust(dist(t(full_z_mean_df)), method = 'ward.D')

png('figs/paper/fig2b.png', width = 300, height=200)
trajs=rownames(full_z_mean_df)[c(20,19)]
tumors=c("LGG_TP",'TGCT_TP','LIHC_TP')
par(mar=c(.5,.5,.5,.5))
par(mfrow=c(2,3))
for(i in trajs
){
  for(l in tumors){
    plot(full_z[full_z$Sub_trajectory_name==i,5:6], 
         pch=19, 
         col=f_colore_rb9_i(full_z[full_z$Sub_trajectory_name==i,l]), 
         axes=F, xlab='', ylab='', cex=.5)    
  }
}
dev.off()


pdf('figs/paper/fig2c.pdf', height = 21, width = 24)
x=pheatmap::pheatmap(full_z_mean_df, cluster_cols = full_z_scores_hcs, cluster_rows = full_z_scores_hct, cutree_cols = 6,cutree_rows = 6,
                     col=c(rev(brewer.pal(9, 'Blues'))[-9],'grey80',
                           brewer.pal(9, 'Reds')[-1]),
                     scale = 'column',
                     annotation_row = annotazioni_t,#fontsize_row = 15,fontsize_col = 15,
                     fontsize = 18,
                     annotation_col = annotazioni_s,
                     labels_row = gsub('primitive_er','Primitive_er',gsub('_trajectory', '',rownames(full_z_mean_df))),
                     labels_col = unlist(lapply(strsplit(colnames(full_z_mean_df), '_'),'[',1)),annotation_colors = mycolors2)
dev.off()

png('figs/paper/fig2d.png', width = 300, height=100)
trajs=rownames(full_z_mean_df)[31]
tumors=c('GBM_NT','GBM_TP')
par(mar=c(.5,.5,.5,.5))
par(mfrow=c(1,3))
plot(full_z[full_z$Sub_trajectory_name==trajs,5:6], 
     pch=19, 
     col=f_colore_vi(full_z[full_z$Sub_trajectory_name==trajs,"development_stage"]), 
     axes=F, xlab='', ylab='', cex=.5)    
plot(full_z[full_z$Sub_trajectory_name==trajs,5:6], 
     pch=19, 
     col=f_colore_rb9_i(full_z[full_z$Sub_trajectory_name==trajs,tumors[1]]), 
     axes=F, xlab='', ylab='', cex=.5)    
plot(full_z[full_z$Sub_trajectory_name==trajs,5:6], 
     pch=19, 
     col=f_colore_rb9_i(full_z[full_z$Sub_trajectory_name==trajs,tumors[2]]), 
     axes=F, xlab='', ylab='', cex=.5)    

dev.off()


pdf('figs/paper/fig2e.pdf')
ggplot(data=devtime_enrichment,aes(x=tissue,fill=Embryonic_Period,y=value))+
  geom_bar(stat='identity',position = 'dodge')+labs(y='Enrichment',x='Embryonic Period',fill='Sample')+
  theme_classic()+theme(legend.position = 'bottom',text = element_text(size=20,color = 'black'),
                        axis.line = element_line(colour = 'black',size=1),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color = "black"),
                        axis.ticks.length.y = unit(.25, "cm"),axis.ticks.length.x = unit(.25, "cm"))+scale_fill_viridis(discrete = T)+labs(y='Enrichment',x='Grade',fill='Embryonic Period')
dev.off()


pdf('figs/paper/fig2f.pdf')
#calculation of smooth ecdf on embryonic period score
smoothed=do.call('rbind',lapply(unique(devtime_tissue$tissue),function(x){
  x1=devtime_tissue[devtime_tissue$tissue==x,]
  dens=density(x1$pancan_tissue_score,from=min(devtime_tissue$pancan_tissue_score)-0.0003*diff(range(devtime_tissue$pancan_tissue_score)),
               to=max(devtime_tissue$pancan_tissue_score)+0.0003+diff(range(devtime_tissue$pancan_tissue_score)))
  data.frame(x=dens$x, y=dens$y, cd=cumsum(dens$y)/sum(dens$y), group=x)}))
x=ggplot() +
  geom_line(data=smoothed, aes(x, cd, color=group),size=2) +
  theme_classic()+labs(color='Tissue' , x='Embryonic Period Score',y='Cumulative probability')+xlim(c(14668,15800))+theme(legend.position = 'bottom',text = element_text(size=20,color = 'black'),
                                                                                                                          axis.line = element_line(colour = 'black',size=1),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color = "black"),
                                                                                                                          axis.ticks.length.y = unit(.25, "cm"),axis.ticks.length.x = unit(.25, "cm"))+scale_fill_viridis(discrete = T)
dev.off()


png('figs/paper/figs1d.png', width = 6000, height=4000)
par(mar=c(.5,.5,.5,.5))
par(mfrow=c(56,62))
for(i in full_z_scores_hct$labels[full_z_scores_hct$order]
){
  for(l in full_z_scores_hcs$labels[full_z_scores_hcs$order]){
    plot(full_z[full_z$Sub_trajectory_name==i,5:6], 
         pch=19, 
         col=f_colore_rb9_i(full_z[full_z$Sub_trajectory_name==i,l]), 
         axes=F, xlab='', ylab='', cex=.5)    
  }
}
dev.off()

#subset of tumor and normal samples
full_z_mean_df_nttp=full_z_mean_df[,grep(paste0(gsub('_NT','',grep('_NT',value = T,colnames(full_z_mean_df))),collapse = '|'),colnames(full_z_mean_df))]
full_z_mean_df_nttp=full_z_mean_df_nttp[,grep('_TM', invert = T,colnames(full_z_mean_df_nttp))]

pdf('figs/paper/figs4A.pdf', height = 21, width = 24)
x=pheatmap::pheatmap(full_z_mean_df_nttp, cluster_cols = F, cluster_rows = full_z_scores_hct, gaps_col = seq(from=0,to=46,by=2),cutree_rows = 6,
                     col=c(rev(brewer.pal(9, 'Blues'))[-9],'grey80',
                           brewer.pal(9, 'Reds')[-1]),
                     scale = 'column',
                     annotation_row = annotazioni_t,#fontsize_row = 15,fontsize_col = 15,
                     fontsize = 18,
                     annotation_col = annotazioni_s,
                     labels_row = gsub('primitive_er','Primitive_er',gsub('_trajectory', '',rownames(full_z_mean_df))),
                     labels_col = unlist(lapply(strsplit(colnames(full_z_mean_df_nttp), '_'),'[',1)),annotation_colors = mycolors2)
dev.off()


#GBM and devtime
zz1=full_z[full_z$Sub_trajectory_name=='Neuron_progenitor_trajectory',c("development_stage","GBM_TP","GBM_NT")]
zz1=rbind(data.frame(dev_time=factor(zz1$development_stage,levels = sort(unique(zz1$development_stage))),value=zz1$GBM_TP,tissue='tumor'),
          data.frame(dev_time=factor(zz1$development_stage,levels = sort(unique(zz1$development_stage))),value=zz1$GBM_NT,tissue='normal'))
zz1$value=normalize2(zz1$value, -1, 1)

pdf('figs/paper/figs4B.pdf', height = 21, width = 24)
ggplot(data=zz1,aes(x=dev_time,fill=tissue,y=value))+
  geom_violin(position = position_dodge(width = .9), width=1.5)+
  labs(y='Similarity',x='Embryonic Period',fill='Sample')+
  theme_classic()+theme(legend.position = 'bottom',text = element_text(size=20,color = 'black'),
                        axis.line = element_line(colour = 'black',size=1),axis.text.x = element_text(color = "black"),
                        axis.ticks.length.y = unit(.25, "cm"),axis.ticks.length.x = unit(.25, "cm"))+stat_summary(fun.y='mean', position = position_dodge(width = .9), col='black')+stat_compare_means(aes(group=tissue), label='p.format',label.y = 1.1, size=5)
dev.off()
